// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBrDQuRt9CHw-DKyNRJorOiHjclr9-vrJE",
      authDomain: "galdinos-secret-santa.firebaseapp.com",
      projectId: "galdinos-secret-santa",
      storageBucket: "galdinos-secret-santa.firebasestorage.app",
      messagingSenderId: "786022998658",
      appId: "1:786022998658:web:5e5f0997e2bffd3126ca9b",
      measurementId: "G-GS1W302SWY"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWwJBBFr_4Rig6oyoyl5v0rtosZ7RFolU',
    appId: '1:786022998658:android:fd003d82d6dced8426ca9b',
    messagingSenderId: '786022998658',
    projectId: 'galdinos-secret-santa',
    storageBucket: 'galdinos-secret-santa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlCKelnkZe3AMyB_TzZrvJuHdFVAzuNvI',
    appId: '1:786022998658:ios:23e20ae05dace86b26ca9b',
    messagingSenderId: '786022998658',
    projectId: 'galdinos-secret-santa',
    storageBucket: 'galdinos-secret-santa.firebasestorage.app',
    iosClientId: '786022998658-duagrvlgg5nppp4tk0bnecu568kkbs4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.secretSanta',
  );
}
